//menus
export const CHANGE_COUNT_FLAG = 'CHANGE_COUNT_FLAG';
export const SAVE_SALED_FOODS = 'SAVE_SALED_FOODS';
export const SAVE_NO_OPEN = 'SAVE_NO_OPEN';
export const SAVE_MENUS_LIST = 'SAVE_MENUS_LIST';
export const SAVE_SHOP_MENU_EXTRA = 'SAVE_SHOP_MENU_EXTRA'; // menu_list内的extra
export const REDUCE_MENUS_LIST_COUNT = 'REDUCE_MENUS_LIST_COUNT';
export const CLEAR_MENUS_LIST_COUNT = 'CLEAR_MENUS_LIST_COUNT';
export const ADD_ITEM_COUNT = 'ADD_ITEM_COUNT';
export const REDUCE_ITEM_COUNT = 'REDUCE_ITEM_COUNT';
// other
export const CHANGE_SHOP_INFO = 'CHANGE_SHOP_INFO';
export const CHANGE_MENUS_TYPE_SETTING = 'CHANGE_MENUS_TYPE_SETTING';
export const CHANGE_USER_SHOP_ORDER = 'CHANGE_USER_SHOP_ORDER';
//foodAttr
export const ADD_GOODS_INFO_ZHE = 'ADD_GOODS_INFO_ZHE';
export const DELEA_GOODS_INFO_ZHE = 'DELEA_GOODS_INFO_ZHE';
export const SALED_CLEAR_GOODS_INFO = 'SALED_CLEAR_GOODS_INFO';
export const CHANGE_FA_MODEL = 'CHANGE_FA_MODEL';
export const SAVE_FOOD_ATTR = 'SAVE_FOOD_ATTR';
export const CHANGE_UNIT = 'CHANGE_UNIT';
export const CHANGE_ASK = 'CHANGE_ASK';
export const INIT_GOODS_INFO = 'INIT_GOODS_INFO';
export const SAVE_GOODS_INFO_MONEY = 'SAVE_GOODS_INFO_MONEY';
export const CLEAR_GOODS_INFO_MONEY = 'CLEAR_GOODS_INFO_MONEY';
export const SAVE_GOODS_INFO = 'SAVE_GOODS_INFO';
export const CLEAR_SEND_GOODS_INFO = 'CLEAR_SEND_GOODS_INFO';
export const ADD_SEND_GOODS_INFO = 'ADD_SEND_GOODS_INFO';
export const CHANGE_GOODS_INFO = 'CHANGE_GOODS_INFO';
export const CLEAR_GOODS_INFO = 'CLEAR_GOODS_INFO';
export const ADD_GOODS_INFO_COUNT = 'ADD_GOODS_INFO_COUNT';
export const REDUCE_GOODS_INFO_COUNT = 'REDUCE_GOODS_INFO_COUNT';
export const REDUCE_ID_GOODS_INFO_COUNT = 'REDUCE_ID_GOODS_INFO_COUNT';

//cart
export const CHANGE_CART_BTN_COLOR = 'CHANGE_CART_BTN_COLOR';
export const CHANGE_CARD_SHOW = 'CHANGE_CARD_SHOW';
export const SAVE_CACHE = 'SAVE_CACHE';
export const SAVE_PAID_AMOUNT = 'SAVE_PAID_AMOUNT';
export const SAVE_SECOND_PRICE = 'SAVE_SECOND_PRICE';
export const SAVE_BARGAIN_PRICE = 'SAVE_BARGAIN_PRICE';
export const CHANGE_TIPS_ISSHOW = 'CHANGE_TIPS_ISSHOW';

//activity
export const SAVE_ACTIVITY_LIST = 'SAVE_ACTIVITY_LIST';
// export const SAVE_ACTIVITY_SHOW = 'SAVE_ACTIVITY_SHOW';
// export const SAVE_ACTIVITY_TIP = 'SAVE_ACTIVITY_TIP';
export const SAVE_MONEY = 'SAVE_MONEY';
export const SAVE_ACT_MESSAGE = 'SAVE_ACT_MESSAGE';

// home
export const SAVE_CITY = 'SAVE_CITY';
export const SAVE_ADDRESS = 'SAVE_ADDRESS';
export const SAVE_LOCATION = 'SAVE_LOCATION';
export const SAVE_CITY_CODE = 'SAVE_CITY_CODE';